
spring:
  application:
    name: ai-neurysm-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 3000

logging:
  level:
    com.aineurysm: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET:mi_clave_secreta_jwt_super_segura_para_desarrollo_que_debe_tener_al_menos_512_bits_para_HS512_algoritmo_jwt_token_provider}
  expiration: 86400000 # 24 horas en milisegundos

app:
  upload-dir: uploads/
  frontend-url: ${FRONTEND_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
